//
//  AlphaIcons.h
//  ProjectName
//
//  Created by AuthorName on 11/12/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface AlphaIcons : NSObject

// Drawing Methods
+ (void)drawSettingsWithFrame: (CGRect)frame;
+ (void)drawFeedBackWithFrame: (CGRect)frame;
+ (void)drawFavoriteWithFrame: (CGRect)frame;
+ (void)drawHistoryWithFrame: (CGRect)frame;
+ (void)drawShareWithFrame: (CGRect)frame;
+ (void)drawDefaultBorderWithFrame: (CGRect)frame;
+ (void)drawBorderWithIndicatorWithFrame: (CGRect)frame fraction: (CGFloat)fraction scale: (CGFloat)scale;
+ (void)drawMaskViewWithFrame: (CGRect)frame;
+ (void)drawThemeColorWithFrame: (CGRect)frame;
+ (void)drawColorBallWithFrame: (CGRect)frame;
+ (void)drawBackArrowWithFrame: (CGRect)frame;
+ (void)drawThemeColorNightModeWithFrame: (CGRect)frame;
+ (void)drawPauseButtonWithFrame: (CGRect)frame;
+ (void)drawPlayButtonWithFrame: (CGRect)frame;
+ (void)drawProfileUnselectedWithFrame: (CGRect)frame;
+ (void)drawPagesUnselectedWithFrame: (CGRect)frame;
+ (void)drawHorizonUnselectedWithFrame: (CGRect)frame;
+ (void)drawHorizonSelectedWithFrame: (CGRect)frame;
+ (void)drawProfileSelectedWithFrame: (CGRect)frame;
+ (void)drawPagesSelectedWithFrame: (CGRect)frame;
+ (void)drawHomeWithFrame: (CGRect)frame;
+ (void)drawBackWithFrame: (CGRect)frame;
+ (void)drawNightModeWithFrame: (CGRect)frame;
+ (void)drawDayModeWithFrame: (CGRect)frame;
+ (void)drawFullScreenButtonWithFrame: (CGRect)frame;
+ (void)drawFullScreenButtonReverseWithFrame: (CGRect)frame;
+ (void)drawFavoriteModernizedWithFrame: (CGRect)frame;
+ (void)drawHistoryModernizedWithFrame: (CGRect)frame;
+ (void)drawFeedBackModernizedWithFrame: (CGRect)frame;
+ (void)drawSettingsModernizedWithFrame: (CGRect)frame;
+ (void)drawPortraitModernizedWithFrame: (CGRect)frame;
+ (void)drawShareModernizedWithFrame: (CGRect)frame;
+ (void)drawDayWithFrame: (CGRect)frame;
+ (void)drawNightWithFrame: (CGRect)frame;
+ (void)drawWelcomePageWithFrame: (CGRect)frame;
+ (void)drawBookWithFrame: (CGRect)frame;
+ (void)drawQualityGoodsWithFrame: (CGRect)frame;

// Generated Images
+ (UIImage*)imageOfSettingsWithFrame: (CGRect)frame;
+ (UIImage*)imageOfFeedBackWithFrame: (CGRect)frame;
+ (UIImage*)imageOfFavoriteWithFrame: (CGRect)frame;
+ (UIImage*)imageOfHistoryWithFrame: (CGRect)frame;
+ (UIImage*)imageOfShareWithFrame: (CGRect)frame;
+ (UIImage*)imageOfDefaultBorderWithFrame: (CGRect)frame;
+ (UIImage*)imageOfBorderWithIndicatorWithFrame: (CGRect)frame fraction: (CGFloat)fraction scale: (CGFloat)scale;
+ (UIImage*)imageOfMaskViewWithFrame: (CGRect)frame;
+ (UIImage*)imageOfThemeColorWithFrame: (CGRect)frame;
+ (UIImage*)imageOfColorBallWithFrame: (CGRect)frame;
+ (UIImage*)imageOfBackArrowWithFrame: (CGRect)frame;
+ (UIImage*)imageOfThemeColorNightModeWithFrame: (CGRect)frame;
+ (UIImage*)imageOfPauseButtonWithFrame: (CGRect)frame;
+ (UIImage*)imageOfPlayButtonWithFrame: (CGRect)frame;
+ (UIImage*)imageOfProfileUnselectedWithFrame: (CGRect)frame;
+ (UIImage*)imageOfPagesUnselectedWithFrame: (CGRect)frame;
+ (UIImage*)imageOfHorizonUnselectedWithFrame: (CGRect)frame;
+ (UIImage*)imageOfHorizonSelectedWithFrame: (CGRect)frame;
+ (UIImage*)imageOfProfileSelectedWithFrame: (CGRect)frame;
+ (UIImage*)imageOfPagesSelectedWithFrame: (CGRect)frame;
+ (UIImage*)imageOfHomeWithFrame: (CGRect)frame;
+ (UIImage*)imageOfBackWithFrame: (CGRect)frame;
+ (UIImage*)imageOfNightModeWithFrame: (CGRect)frame;
+ (UIImage*)imageOfDayModeWithFrame: (CGRect)frame;
+ (UIImage*)imageOfFullScreenButtonWithFrame: (CGRect)frame;
+ (UIImage*)imageOfFullScreenButtonReverseWithFrame: (CGRect)frame;
+ (UIImage*)imageOfFavoriteModernizedWithFrame: (CGRect)frame;
+ (UIImage*)imageOfHistoryModernizedWithFrame: (CGRect)frame;
+ (UIImage*)imageOfFeedBackModernizedWithFrame: (CGRect)frame;
+ (UIImage*)imageOfSettingsModernizedWithFrame: (CGRect)frame;
+ (UIImage*)imageOfPortraitModernizedWithFrame: (CGRect)frame;
+ (UIImage*)imageOfShareModernizedWithFrame: (CGRect)frame;
+ (UIImage*)imageOfDayWithFrame: (CGRect)frame;
+ (UIImage*)imageOfNightWithFrame: (CGRect)frame;
+ (UIImage*)imageOfWelcomePageWithFrame: (CGRect)frame;
+ (UIImage*)imageOfBookWithFrame: (CGRect)frame;
+ (UIImage*)imageOfQualityGoodsWithFrame: (CGRect)frame;

@end
